language: node_js
node_js:
- 10.16.3
script: ng build --project ng-bootstrap-form-validation
before_deploy: node ./scripts/beforeDeploy && cd dist/ng-bootstrap-form-validation
deploy:
  - provider: npm
    skip_cleanup: true
    email: kevin.kipp@gmail.com
    api_key:
      secure: g6exdiLaFPKkBdtSy87kaH/bVb2bceglkgxi2pQOIavX6Uo5+Kd3Xw37q/R9sVy0s2AVIiF1qTLQnt+lWS5k4Dsd1IISk0ywXutE4VRvuMqCiAcmlfxIYKoDgoezGXEK5Jq/x+e32VRBryBMfW+IfOZR3yOaHb7rvTf+lF5Q1RIe0HhXs7kD/Kr74qDJWJtA/BmFVE17k6b2l1jFDpcE8MS+UR32hMJ6BGD2OYIulKJ2tIDPAUKJQgDaYD+iPJOJWt89uJhDQtadm6/ib5zLEtGtKrZO4nDYwQ3OkAWG3IzoFJg0tkfvEAecslsDJSGVzO2aaIaUmClXrR8oaitavETtlza3R7qfvMGaB9Mp9pHlVjyn2FlmrNsb6pNEUY0HMRaiurc0Esey4hY8Dr0qqG16rnUsV/fIJngz+PdU/GV4vdsS01E2LyPzTyyk4drUZGVJVJszijeouxxb8rsOGnT+ZQwguDcFYkoreXVdBUcwtYClGtyBV5dq2cGCdMoSWTv0VRm7Rxywt3VR8pSiCXwaDIF6bpHLZ+VAWjs3amIht1htUuJTfj1qLDoVrUvzKRbKn6Y29PA7fGcD0Q3eKswuOVD5FXRIbofssTRa/KeFi9Hjsw/sAbOuwMkvq7oD57dZIA8V1ONrLZJU+jrfBU4Ea4q9Ue13c8IJRofnE58=
    on:
      tags: true
      repo: third774/ng-bootstrap-form-validation
  - provider: npm
    skip_cleanup: true
    tag: next
    email: kevin.kipp@gmail.com
    api_key:
      secure: g6exdiLaFPKkBdtSy87kaH/bVb2bceglkgxi2pQOIavX6Uo5+Kd3Xw37q/R9sVy0s2AVIiF1qTLQnt+lWS5k4Dsd1IISk0ywXutE4VRvuMqCiAcmlfxIYKoDgoezGXEK5Jq/x+e32VRBryBMfW+IfOZR3yOaHb7rvTf+lF5Q1RIe0HhXs7kD/Kr74qDJWJtA/BmFVE17k6b2l1jFDpcE8MS+UR32hMJ6BGD2OYIulKJ2tIDPAUKJQgDaYD+iPJOJWt89uJhDQtadm6/ib5zLEtGtKrZO4nDYwQ3OkAWG3IzoFJg0tkfvEAecslsDJSGVzO2aaIaUmClXrR8oaitavETtlza3R7qfvMGaB9Mp9pHlVjyn2FlmrNsb6pNEUY0HMRaiurc0Esey4hY8Dr0qqG16rnUsV/fIJngz+PdU/GV4vdsS01E2LyPzTyyk4drUZGVJVJszijeouxxb8rsOGnT+ZQwguDcFYkoreXVdBUcwtYClGtyBV5dq2cGCdMoSWTv0VRm7Rxywt3VR8pSiCXwaDIF6bpHLZ+VAWjs3amIht1htUuJTfj1qLDoVrUvzKRbKn6Y29PA7fGcD0Q3eKswuOVD5FXRIbofssTRa/KeFi9Hjsw/sAbOuwMkvq7oD57dZIA8V1ONrLZJU+jrfBU4Ea4q9Ue13c8IJRofnE58=
    on:
      branch: master
      repo: third774/ng-bootstrap-form-validation
